exclude: |
  (?x)^(
    ibgedatadownloader/.*\.qml|
    ibgedatadownloader/.*\.ui|
    ibgedatadownloader/.*ui_[\w\d]*\.py|
    requirements/.*\.txt
  )$

default_language_version:
  python: python3.9

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=500
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        args:
          - --assume-in-merge
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args:
          - --settings-path=pyproject.toml

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      # - id: ruff-check
      #   args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
      - id: sphinx-lint

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-black~=0.1
          - mdformat-footnote~=0.1
          - mdformat-frontmatter~=2.0
          - mdformat-gfm~=0.3
          - mdformat-toc~=0.3

  - repo: local
    hooks:
      - id: atualiza_metadata
        name: Atualiza campo version do metadata.txt com última versão do CHANGELOG.md
        entry: python scripts/atualiza_metadata.py
        language: python
        files: CHANGELOG.md
        additional_dependencies:
          - qgis-plugin-ci~=2.8.10
