name: "🚀 Releaser"

on:
  push:
    tags:
      - "*"

env:
  PYTHON_VERSION: 3.12

permissions:
  contents: write  # Permite criar releases e tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install qgis-plugin-ci
          if [ -f requirements/packaging.txt ]; then pip install -r requirements/packaging.txt; fi

      - name: Deploy plugin (Release & Repo)
        run: >-
          qgis-plugin-ci
          release ${GITHUB_REF/refs\/tags\//}
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --create-plugin-repo
          --osgeo-username ${{ secrets.OSGEO_USERNAME }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
