name: "🚀 Releaser"

on:
  push:
    tags:
      - "*"

env:
  PYTHON_VERSION: 3.12

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Importante para gerar changelog completo baseado em git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install qgis-plugin-ci
          if [ -f requirements/packaging.txt ]; then pip install -r requirements/packaging.txt; fi

      - name: Generate Changelog
        run: |
          # Gera o changelog da versão atual e salva no arquivo release.md
          qgis-plugin-ci changelog ${GITHUB_REF/refs\/tags\//} > release.md
          # Adiciona uma quebra de linha visual antes da lista automática
          echo -e "\n" >> release.md

          # (Opcional) Mostra o conteúdo no log para debug
          cat release.md

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          echo "Criando release para tag ${GITHUB_REF/refs\/tags\//}..."
          # Usa --notes-file para pegar o texto gerado acima
          gh release create ${GITHUB_REF/refs\/tags\//} \
            --title "Release ${GITHUB_REF/refs\/tags\//}" \
            --notes-file release.md \
            || true

      - name: Deploy plugin (Release & Repo)
        run: >-
          qgis-plugin-ci
          release ${GITHUB_REF/refs\/tags\//}
          --github-token ${{ secrets.RELEASE_TOKEN }}
          --create-plugin-repo
          --osgeo-username ${{ secrets.OSGEO_USERNAME }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
